// Shared types for Antfarm — visual task pipeline for Claude Code

export type SpecTemplateType = 'general' | 'api_endpoint' | 'ui_component' | 'refactor' | 'bugfix';

export const SPEC_TEMPLATES: { type: SpecTemplateType; label: string; description: string }[] = [
  { type: 'general', label: 'General', description: 'Default template for any task' },
  { type: 'api_endpoint', label: 'API Endpoint', description: 'REST/GraphQL endpoint with request/response contracts' },
  { type: 'ui_component', label: 'UI Component', description: 'React component with props, states, and accessibility' },
  { type: 'refactor', label: 'Refactor', description: 'Code restructuring with before/after comparison' },
  { type: 'bugfix', label: 'Bugfix', description: 'Bug fix with reproduction steps and root cause analysis' },
];

// Parses the template type from a card's context field
export function parseTemplateType(context: string | null): SpecTemplateType {
  const match = context?.match(/^\[template:(\w+)\]/);
  const type = match?.[1];
  if (type && SPEC_TEMPLATES.some(t => t.type === type)) return type as SpecTemplateType;
  return 'general';
}

// Returns the label for a template type
export function getTemplateLabel(type: SpecTemplateType): string {
  return SPEC_TEMPLATES.find(t => t.type === type)?.label ?? 'General';
}

export type AgentStatus = 'idle' | 'working' | 'waiting' | 'errored' | 'completed';
export type NoteSource = 'user' | 'agent';
export type NoteType = 'note' | 'output' | 'status_change' | 'human_review_request';
export type Actor = 'user' | 'agent';

// Pipeline stages that map to board columns
export type PipelineStage = 'idea' | 'speccing' | 'spec_ready' | 'planning' | 'plan_review' | 'building' | 'reviewing' | 'done';
export type SpecStatus = 'pending' | 'generating' | 'ready' | 'approved';
export type PlanStatus = 'none' | 'generating' | 'ready' | 'approved' | 'failed';
export type ModelName = string;

// Column name to pipeline stage mapping
export const PIPELINE_COLUMNS: { name: string; stage: PipelineStage; color: string }[] = [
  { name: 'Idea', stage: 'idea', color: '#6b7280' },
  { name: 'Speccing', stage: 'speccing', color: '#6366f1' },
  { name: 'Spec Ready', stage: 'spec_ready', color: '#8b5cf6' },
  { name: 'Planning', stage: 'planning', color: '#a855f7' },
  { name: 'Plan Review', stage: 'plan_review', color: '#d946ef' },
  { name: 'Building', stage: 'building', color: '#3b82f6' },
  { name: 'Reviewing', stage: 'reviewing', color: '#f97316' },
  { name: 'Done', stage: 'done', color: '#22c55e' },
];

// Structured implementation plan generated by the planning agent
export interface ImplementationPlan {
  id: number;
  card_id: number;
  version: number;
  files_to_create: Array<{ path: string; purpose: string }>;
  files_to_modify: Array<{ path: string; changes: string }>;
  steps: Array<{ order: number; description: string; files: string[] }>;
  estimated_scope: 'small' | 'medium' | 'large';
  dependencies: string[];
  feedback: string | null;
  created_at: string;
}

export interface Chain {
  id: number;
  board_id: number;
  name: string;
  created_at: string;
}

export interface Board {
  id: number;
  name: string;
  directory: string | null; // project root directory
  max_concurrency: number;
  default_model: ModelName;
  created_at: string;
  updated_at: string;
}

export interface Column {
  id: number;
  board_id: number;
  name: string;
  position: number;
  color: string | null;
}

export interface Card {
  id: number;
  column_id: number;
  title: string;
  description: string | null;
  context: string | null;
  files: string | null;
  directory_path: string | null;
  git_branch: string | null;
  agent_status: AgentStatus;
  assigned_session: string | null;
  last_activity_at: string | null;
  archived: boolean;
  created_at: string;
  updated_at: string;
  position: number;
  // Pipeline-specific fields
  spec: string | null;
  spec_status: SpecStatus;
  plan_status: PlanStatus;
  pr_url: string | null;
  pr_branch: string | null;
  worktree_path: string | null;
  claude_session_id: string | null;
  // Chain + model fields
  chain_id: number | null;
  chain_position: number | null;
  model: ModelName | null;
  auto_pilot: boolean;
}

export interface CardDep {
  id: number;
  card_id: number;
  depends_on_card_id: number;
}

export interface Subtask {
  id: number;
  card_id: number;
  text: string;
  completed: boolean;
  position: number;
}

export interface Note {
  id: number;
  card_id: number;
  content: string;
  source: NoteSource;
  type: NoteType;
  created_at: string;
}

export interface ActivityLog {
  id: number;
  card_id: number | null;
  action: string;
  actor: Actor;
  details_json: string | null;
  created_at: string;
}

// MCP tool response shapes
export interface ToolSuccess<T = unknown> {
  success: true;
  data: T;
}

export interface ToolError {
  success: false;
  error: string;
}

export type ToolResponse<T = unknown> = ToolSuccess<T> | ToolError;

export interface ClaimResult {
  claimed: boolean;
  reason?: 'already_claimed' | 'not_found' | 'has_blockers';
  card?: Card;
}

// SSE event types sent to dashboard
export type SSEEventType =
  | 'card.created'
  | 'card.completed'
  | 'card.unblocked'
  | 'card.claimed'
  | 'card.blocked'
  | 'card.errored'
  | 'card.updated'
  | 'card.moved'
  | 'card.spec_ready'
  | 'card.plan_generating'
  | 'card.plan_ready'
  | 'card.plan_approved'
  | 'card.plan_rejected'
  | 'card.plan_failed'
  | 'card.pr_ready'
  | 'board.updated'
  | 'pool_status';

export interface SSEEvent {
  type: SSEEventType;
  card_id?: number;
  data: Record<string, unknown>;
  timestamp: string;
}
